### ISSUE TITLE
Enchancements to NMAPAutoAnalyzer

### ISSUE THREAD

**Issue by Raytri3** [raesene/TestingScripts#1]
Excuse my ruby ignorance, but I tried adding a few items to the report section by modifying the ruby code (I wanted to put totals in Active and Inactive) by adding active_ipaddresses.count. However when I run autoanalyzer after the change - I don't see my input. Is there something else I need to do once I have modified the ruby code?

**Comment by raesene** [comment]
Hi, 
it'll depend on exactly how you've modified the code.  If you could show me a copy of the updated script (perhaps create a gist of it, or put it on pastebin) I could probably give you some pointers.
